// <auto-generated />
using EfCoreSandbox;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EfCoreSandbox.Migrations
{
    [DbContext(typeof(AgentContext))]
    partial class AgentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EfCoreSandbox.Model.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Owner");

                    b.HasKey("Id");

                    b.ToTable("Agent");
                });

            modelBuilder.Entity("EfCoreSandbox.Model.Capability", b =>
                {
                    b.Property<int>("AgentId");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("AgentId", "Name");

                    b.ToTable("Capability");
                });

            modelBuilder.Entity("EfCoreSandbox.Model.Capability", b =>
                {
                    b.HasOne("EfCoreSandbox.Model.Agent")
                        .WithMany("Capabilities")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
